### ISSUE TITLE
Does it block when apps or the OS bypass the router DNS?

### ISSUE THREAD

**Issue by ramgp** [britannic/blacklist#21]
Does it block something like this `nslookup doubleclick.net 9.9.9.9`?
Does it block for IPv6 requests?

**Comment by britannic** [comment]
The integration doesn’t do any blocking, however it will produce dnsmasq configuration files. So whatever dnsmasq supports with DNS lookup rewrites is possible. Not sure of your use case, since 9.9.9.9 is a legit DNS service, but, yes, dnsmasq can rewrite the response to any DNS request using it as a nameserver. For IPv6, please refer to the dnsmasq documentation.
